### ISSUE TITLE
Modifier le comportement input de la task

### ISSUE THREAD

**Issue by billykiwee** [yoann90/Todo#27]
### Description
Actuellement, une tâche peut être ajoutée en cliquant sur le bouton dédié. Cependant, il serait pratique de permettre l'ajout d'une tâche en appuyant sur la touche "Entrée". Cette modification améliorera l'ergonomie et la rapidité d'utilisation de l'application.

### Tâches
- [x] Modifier ou ajouter la fonction qui permet de modifier le texte de la tâche pour qu'elle prenne également en compte la validation via la touche "Entrée".
- [x] Modifier également le comportement au onblur => l'édit est terminé
- [x] Assurer qu'on ne puisse plus cliqué sur les autres boutons lors de l'édition pour éviter les problèmes.
- [x] Modifier le comportement CSS.
- [x] Assurer que le comportement actuel du bouton pour l'ajout de tâches reste inchangé.
- [x] Tester le nouveau comportement pour garantir que l'ajout de tâches fonctionne correctement avec la touche "Entrée".

### Résultat attendu
L'utilisateur pourra modifier une tâche en appuyant sur "Entrée" après avoir écrit dans l'input, en plus de l'option actuelle de cliquer sur le bouton.

**Comment by billykiwee** [comment]
dqvsdbds

**Comment by auraalex21** [comment]
Review faite 

point a regler : 
souci au moment d'ajouter un long text les svg sorte de la box 
sinon le reste good 


![Image](https://github.com/user-attachments/assets/25de3f28-b207-40db-a0f6-438307d3b5b6)

**Comment by auraalex21** [comment]
Review faite et tout et ok pour moi

**Comment by GohanJesse** [comment]
Quelques petites chose à revoir pour parfaire le ticket et sa validation : 

- [  ] Ajout j'un padding au textarea
- [x] Ajout du radius des angles du textarea pour être au plus proche de ce qui est demandé.
- [x] Supression de la barre de scroll

ce qui est demandé : 

![Image](https://github.com/user-attachments/assets/acfae473-ec3f-49be-a00b-e7165c164b60)

Textarea actuel : 



![Image](https://github.com/user-attachments/assets/6ea24e88-684c-4520-a476-4ed5b55fb4eb)
