### ISSUE TITLE
Ajouter un header avec titre et toggle light/dark theme

### ISSUE THREAD

**Issue by GohanJesse** [yoann90/Todo#38]
## Contexte

Nous souhaitons ajouter un header à l'application pour améliorer la cohérence visuelle avec la maquette et offrir une meilleure structuration de l'interface utilisateur. Ce header inclura le titre de l'application et un toggle pour basculer entre les thèmes clair et sombre.

## Détails fonctionnels

**Le header doit contenir :**

Titre de l'application : Afficher le titre "KiweeTodo" en deux couleurs distinctes, "Kiwee" en belge (#deccb0) et "Todo" en orange (#f55932), positionné à gauche du header.
Toggle light/dark theme : Intégrer un toggle avec une icône de lune pour le mode sombre et une icône de soleil pour le mode clair, placé à droite du header.

## Design et style

Le header doit respecter le style visuel de la maquette fournie, avec les mêmes couleurs, typographies, marges, et espacements.
Il est impératif que le header soit responsive, c’est-à-dire qu’il s'adapte correctement aux différentes tailles d'écrans (mobile, tablette, desktop).
Le header doit être en HTML et CSS et doit respecter la sémantique bien entendu (balise header plutôt qu'un div).

## Toggle light/dark :

Le toggle doit inclure deux icônes : lune pour le mode sombre et soleil pour le mode clair.
Le toggle doit avoir une petite boule glissante (slider) qui se déplace entre les icônes en fonction du thème actif.
Lorsque le mode sombre est actif, la boule doit se positionner sur l'icône de la lune. Lorsque le mode clair est actif, elle doit se positionner sur l'icône du soleil.

## Comportement

**Animation :**

L'animation du toggle doit être fluide et intuitive, avec un déplacement doux de la boule glissante d'une icône à l'autre.

## Délivrables

- [x] Mise en place du header avec le titre "KiweeTodo" conformément à la maquette (positionnement et couleurs respectés).
- [x] Implémentation du toggle light/dark dans le header, avec gestion des icônes et du slider.
- [x] Intégration de la logique CSS pour basculer entre les thèmes en utilisant des classes spécifiques (ex. : light-theme et dark-theme).
- [x] Vérification de la compatibilité du header et du toggle sur différentes tailles d'écran pour assurer le responsive design.

## Critères d'acceptation

- [ ] Le header est conforme à la maquette et s'adapte aux différents écrans.
- [ ] Le style du header est homogène avec le reste de l'application et suit les directives visuelles fournies.
- [ ] Le toggle est correctement aligné à droite dans le header avec le titre et fonctionne pour basculer entre les thèmes clair et sombre.
- [ ] Les icônes de la lune et du soleil sont bien visibles et distinctes dans chaque thème.
- [ ] L'animation du toggle est  fluide et intuitive, avec un déplacement doux de la boule glissante d'une icône à l'autre.

## Sources
Le toggle dark theme doit être de ce style
![Image](https://github.com/user-attachments/assets/281df641-05d0-423c-bfdd-9b4534df368e)

**Comment by Softexus** [comment]
review ✅

**Comment by billykiwee** [comment]
# Point à revoir ⚠️

- [x] La couleur du logo (texte)
- [x] La max with de la div dans le header (Les élements doivent être à peut près comme les ticket= au milieu)
- [ ] Fixer au top de l'écran
- [x] améliorer le toggle (au mieux)

**Comment by Softexus** [comment]
# Point à revoir ⚠️
- [x] Le header est correctement aligné
- [x] Le toggle contient des svg pour la lune et le soleil (se référé a la source plus haut)

**Comment by Softexus** [comment]
review ✅

**Comment by billykiwee** [comment]
## Point à revoir ⚠️
- [x] Mettre la couleur du bouton en orange (comme le thème principal) et les svg lune-soleil en blanc
- [x] Réduire la taille du toggle
➡️ Détails donnés ici dans la conv discord : https://discord.com/channels/1141045106749735073/1268573142717038682/1275406524893626388
- [x] Mettre le text du header en H2
