### ISSUE TITLE
Créer une modal pour la création et la personnalisation des tâches

### ISSUE THREAD

**Issue by GohanJesse** [yoann90/Todo#43]
## Contexte
Nous souhaitons permettre aux utilisateurs de personnaliser leurs tâches lors de leur création et de leur modification. La modal permettra aux utilisateurs de définir le texte de la tâche, de choisir une date limite (deadline), et de sélectionner une couleur pour la tâche. Cela contribuera à une meilleure organisation et priorisation des tâches.

## Détails fonctionnels

**Lorsqu'une tâche est créée ou modifiée, ouvrir une modal avec les options suivantes :**

**Texte de la tâche :** L'utilisateur peut entrer ou modifier le titre de la tâche.
**Date limite (deadline) :** L'utilisateur peut définir une date limite pour la tâche.
**Couleur de la tâche :** L'utilisateur peut sélectionner une couleur pour personnaliser visuellement la tâche.

Les modifications ou les nouveaux attributs définis dans la modal doivent être appliqués immédiatement après validation et être persistants (même après un rafraîchissement de la page).

**La modal sera réutilisée pour les deux cas d'utilisation suivants :**

**Création de tâche :** L'utilisateur définit les attributs initiaux (texte, deadline, couleur) lors de l'ajout d'une nouvelle tâche.
**Modification de tâche :** L'utilisateur peut modifier les attributs existants d'une tâche (texte, deadline, couleur).

## Délivrables

- [x] Implémentation d'une modal permettant à l'utilisateur de personnaliser les tâches lors de leur création et modification.
- [x] Gestion de la logique via JavaScript pour créer ou modifier les tâches en fonction des valeurs saisies dans la modal.
- [x] Mise à jour des objets todos pour stocker les valeurs du texte, de la couleur, et de la date limite.

## Critères d'acceptation

- [x] L'utilisateur peut définir ou modifier le texte, la date limite et la couleur d'une tâche via la modal.
- [x] Les modifications ou les nouvelles tâches sont enregistrées et appliquées immédiatement.
- [x] Les informations saisies persistent après un rafraîchissement de la page.

## Sources 
Exemple de modal avec les infos qu'on doit entrer : 
- Description / titre
- Deadline (une date au format : 12 Jan 2024)
- Une couleur
![Image](https://github.com/user-attachments/assets/6315dacc-e8fe-41fd-86aa-c7cd334f3c5d)

**Comment by auraalex21** [comment]
## souci :

on peut pas cliquer sur "entrer" pour ajouter la tache

quand on cheque sa casse tout et on peut plus retirer le cheque :

![Image](https://github.com/user-attachments/assets/f89b3128-f093-4660-9753-e33bda6f93e0)


souci d'alignement sur les bouton du dessou :

![Image](https://github.com/user-attachments/assets/d6ce4121-a562-4f46-bea0-6699e6dcf902)

responsive mauvais :

![Image](https://github.com/user-attachments/assets/efd0daa8-e956-4a08-9370-f2715ecf090d)

boutons "fermer" pas bien centrer :

![Image](https://github.com/user-attachments/assets/4783fdee-919f-447b-8345-e790cc722ccc)
