### ISSUE TITLE
Corriger le compteur de tache

### ISSUE THREAD

**Issue by billykiwee** [yoann90/Todo#52]
### Description
Le compteur de tâche affiche un nombre incorrect de tâches complétées/en cours.

### Étapes pour reproduire
1. Créer et compléter plusieurs tâches.
2. Observer le compteur de tâche.

### Comportement attendu
Le compteur doit refléter précisément le nombre de tâches en cours et complétées.

## Tips
Peut être géré directement avec le `tasks.lenght`

**Comment by Softexus** [comment]
Il faut supprimer la var et l'utilisation de la var taskCount seulement le tasks.lenght est attendu

**Comment by Softexus** [comment]
review ✅
