### ISSUE TITLE
Revoir logique dark/theme + ajouter des variables CSS

### ISSUE THREAD

**Issue by billykiwee** [yoann90/Todo#55]
## Mission

- [x] Mettre en place le changement d'état du thème avec le dataset 
- [x] Mettre en place des variable CSS et faire en sorte que toutes les couleurs du css soit en variable (réutilisable), ajuster si besoin 

## Sources 
Logique JS : https://discord.com/channels/1141045106749735073/1268573142717038682/1275791653222879254
Logique CSS : https://discord.com/channels/1141045106749735073/1268573142717038682/1275791728670019665

**Comment by Softexus** [comment]
le css pour le light theme n'est pas bon les couleurs sont illisibles

**Comment by Softexus** [comment]
review ✅
